server:
  port: 8081

eureka:
  instance:
    hostname: eureka8081.com
  client:
    register-with-eureka: false   #false表示不向注册中心注册自己
    fetch-registry: false         #false 表示自己端就是注册中心，我的职责是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://eureka8080.com:8080/eureka/ #注意这个地址为8080的地址
spring:
  application:
    name: eureka-server
